JobPortalApp/Controllers/AplikimsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JobPortalApp.Models;

namespace JobPortalApp.Controllers
{
    public class AplikimsController : Controller
    {
        private JobPortalEntities db = new JobPortalEntities();

        // GET: Aplikims
        public ActionResult Index()
        {
            var aplikims = db.Aplikims.Include(a => a.Kompania).Include(a => a.PozicionPune);
            return View(aplikims.ToList());
        }

        // GET: Aplikims/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Aplikim aplikim = db.Aplikims.Find(id);
            if (aplikim == null)
            {
                return HttpNotFound();
            }
            return View(aplikim);
        }

        // GET: Aplikims/Create
        public ActionResult Create()
        {
            ViewBag.Komp_Id = new SelectList(db.Kompanias, "ID_Kompani", "Emri");
            ViewBag.Pozc_Id = new SelectList(db.PozicionPunes, "Id_Pozicion", "Emri_Poz");
            return View();
        }

        // POST: Aplikims/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id_Aplikim,Pozc_Id,Komp_Id,Orari")] Aplikim aplikim)
        {
            if (ModelState.IsValid)
            {
                db.Aplikims.Add(aplikim);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Komp_Id = new SelectList(db.Kompanias, "ID_Kompani", "Emri", aplikim.Komp_Id);
            ViewBag.Pozc_Id = new SelectList(db.PozicionPunes, "Id_Pozicion", "Emri_Poz", aplikim.Pozc_Id);
            return View(aplikim);
        }

        // GET: Aplikims/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Aplikim aplikim = db.Aplikims.Find(id);
            if (aplikim == null)
            {
                return HttpNotFound();
            }
            ViewBag.Komp_Id = new SelectList(db.Kompanias, "ID_Kompani", "Emri", aplikim.Komp_Id);
            ViewBag.Pozc_Id = new SelectList(db.PozicionPunes, "Id_Pozicion", "Emri_Poz", aplikim.Pozc_Id);
            return View(aplikim);
        }

        // POST: Aplikims/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id_Aplikim,Pozc_Id,Komp_Id,Orari")] Aplikim aplikim)
        {
            if (ModelState.IsValid)
            {
                db.Entry(aplikim).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Komp_Id = new SelectList(db.Kompanias, "ID_Kompani", "Emri", aplikim.Komp_Id);
            ViewBag.Pozc_Id = new SelectList(db.PozicionPunes, "Id_Pozicion", "Emri_Poz", aplikim.Pozc_Id);
            return View(aplikim);
        }

        // GET: Aplikims/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Aplikim aplikim = db.Aplikims.Find(id);
            if (aplikim == null)
            {
                return HttpNotFound();
            }
            return View(aplikim);
        }

        // POST: Aplikims/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Aplikim aplikim = db.Aplikims.Find(id);
            db.Aplikims.Remove(aplikim);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

JobPortalApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JobPortalApp.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        
        
    }
}

JobPortalApp/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<!DOCTYPE html>
<html lang="en">
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
    body, h1, h2, h3, h4, h5, h6 {
        font-family: "Lato", sans-serif
    }

    .w3-bar, h1, button {
        font-family: "Montserrat", sans-serif
    }

    .fa-anchor, .fa-coffee {
        font-size: 200px
    }
</style>
<body>

    <!-- Navbar -->
    <div class="w3-top">
        <div class="w3-bar w3-red w3-card w3-left-align w3-large">
            <a class="w3-bar-item w3-button w3-hide-medium w3-hide-large w3-right w3-padding-large w3-hover-white w3-large w3-red" href="javascript:void(0);" onclick="myFunction()" title="Toggle Navigation Menu"><i class="fa fa-bars"></i></a>
            <a href="#" class="w3-bar-item w3-button w3-padding-large w3-white">Home</a>
            <a href="#" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white">Link 1</a>
            <a href="#" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white">Link 2</a>
            <a href="#" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white">Link 3</a>
            <a href="#" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white">Link 4</a>
        </div>

        <!-- Navbar on small screens -->
        <div id="navDemo" class="w3-bar-block w3-white w3-hide w3-hide-large w3-hide-medium w3-large">
            <a href="#" class="w3-bar-item w3-button w3-padding-large">Pozicionet e Punes</a>
            <a href="#" class="w3-bar-item w3-button w3-padding-large">Apiko</a>
            @*<a href="#" class="w3-bar-item w3-button w3-padding-large">Link 3</a>
            <a href="#" class="w3-bar-item w3-button w3-padding-large">Link 4</a>*@
        </div>
    </div>

    <!-- Header -->
    <header class="w3-container w3-red w3-center" style="padding:128px 16px">
        <h1 class="w3-margin w3-jumbo">My Job Portal</h1>
        <p class="w3-xlarge">Your future is secure with us.</p>
        <input type="button" class="w3-button w3-black w3-padding-large w3-large w3-margin-top" value="Apliko Tani! " onclick='window.location.href = "@Url.Action("Create", "Aplikims")"' />
        
    </header>

    <!-- First Grid -->
    <div class="w3-row-padding w3-padding-64 w3-container">
        <div class="w3-content">
            <div class="w3-twothird">
                <h1>Aplikuesi</h1>
                <h5 class="w3-padding-32"> Your future is in your hands.</h5>

                <p class="w3-text-grey">
                    Portali yne do te jap mundesi qe ju te aplikoni ne pozicionet e punes qe ofrohen nga kompanite me prestigjoze ne vend.
                </p>
            </div>

            <div class="w3-third w3-center">
                <i class="fa fa-anchor w3-padding-64 w3-text-red"></i>
            </div>
        </div>
    </div>

    <!-- Second Grid -->
    <div class="w3-row-padding w3-light-grey w3-padding-64 w3-container">
        <div class="w3-content">
            <div class="w3-third w3-center">
                <i class="fa fa-coffee w3-padding-64 w3-text-red w3-margin-right"></i>
            </div>

            <div class="w3-twothird">
                <h1>HR</h1>
                <h5 class="w3-padding-32"> With us you find the best workers</h5>

                <p class="w3-text-grey">
                    Me portalin tone, ne ofrojme mundesine qe ju te afishoni pozicionet e lira duke minimizuar kohen e humbur qe vjen si pasoje e rekrutimit direkt.
                </p>
            </div>
        </div>
    </div>

    <div class="w3-container w3-black w3-center w3-opacity w3-padding-64">
        <h1 class="w3-margin w3-xlarge">Quote of the day: live life</h1>
    </div>

    <!-- Footer -->
    <footer class="w3-container w3-padding-64 w3-center w3-opacity">
        <div class="w3-xlarge w3-padding-32">
            <i class="fa fa-facebook-official w3-hover-opacity"></i>
            <i class="fa fa-instagram w3-hover-opacity"></i>
            <i class="fa fa-snapchat w3-hover-opacity"></i>
            <i class="fa fa-pinterest-p w3-hover-opacity"></i>
            <i class="fa fa-twitter w3-hover-opacity"></i>
            <i class="fa fa-linkedin w3-hover-opacity"></i>
        </div>
        <p>Powered by Romela Qytyku</p>
    </footer>

    <script>
// Used to toggle the menu on small screens when clicking on the menu button
@*function myFunction() {
  var x = document.getElementById("navDemo");
  if (x.className.indexOf("w3-show") == -1) {
    x.className += " w3-show";
  } else {
    x.className = x.className.replace(" w3-show", "");
  }
}
    </script>*@

</body>
</html>